name: EC2 Access Test

on:
  push:
    branches:
      - main

jobs:
  access-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
          
#       - name: Install SSH client
#         run: sudo apt-get install -y ssh

#       - name: Create PEM file
#         run: |
#           echo "${{ secrets.PEM_KEY }}" > key.pem
#           chmod 400 key.pem

      - name: SSH to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_SERVER_IP }}
          username: ${{ secrets.AWS_SERVER_USER }}
          key: ${{ secrets.PEM_KEY }}
          port: ${{ secrets.AWS_SERVER_SSH_PORT }}
          script: uname -r

